### ISSUE TITLE
Infinite dirt

### ISSUE THREAD

**Issue by abcdefghi39664** [ivangeevo/tough_environment#10]
I'm on version 1.21.1
To replicate: Place a bottom dirt slab  ontop of another bottom dirt slab, the slab at the bottom turns into a full block while the slab at the top stays the same.
Video:
https://github.com/user-attachments/assets/fa0097f9-b419-422d-ad1f-a00616be7df5

**Comment by ivangeevo** [comment]
Most likely you got an older version. Please update to the newest one.

**Comment by abcdefghi39664** [comment]
Im sorry for this issue, you are right, im not even sure how I downloaded an older version my launcher should had chosen the most recent one
